FROM 763104351884.dkr.ecr.us-west-2.amazonaws.com/huggingface-pytorch-inference:2.0.0-transformers4.28.1-gpu-py310-cu118-ubuntu20.04

RUN apt-get -y update && apt-get -y upgrade && apt-get install -y --no-install-recommends ffmpeg